/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regexjava1;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class AbrirArchivoVentana extends javax.swing.JFrame {

    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    /**
     * Creates new form AbrirArchivoVentana
     */
    public AbrirArchivoVentana() {
        initComponents();
    }
    public String abrirArchivo (File archivo){
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascc1;
            while ((ascc1=entrada.read())!=-1){
                char caracter = (char)ascc1;
                documento += caracter;
            }
        }catch(Exception e){ 
        }
        return documento;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirTxt = new javax.swing.JButton();
        regex1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        regex3 = new javax.swing.JButton();
        regex2 = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regex4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AbrirTxt.setBackground(new java.awt.Color(255, 102, 102));
        AbrirTxt.setFont(new java.awt.Font("Broadway", 0, 11)); // NOI18N
        AbrirTxt.setForeground(new java.awt.Color(0, 102, 102));
        AbrirTxt.setText("Open File");
        AbrirTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirTxtActionPerformed(evt);
            }
        });

        regex1.setText("Palabras Similares");
        regex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regex1ActionPerformed(evt);
            }
        });

        TxtArea.setColumns(20);
        TxtArea.setRows(5);
        jScrollPane1.setViewportView(TxtArea);

        jLabel1.setText("Lista de opciones");

        regex3.setText("Buscar y reemplazar");
        regex3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regex3ActionPerformed(evt);
            }
        });

        regex2.setText("Minisculas/Mayusculas");
        regex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regex2ActionPerformed(evt);
            }
        });

        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado de la seleccion");

        regex4.setText("Expresion matematica");
        regex4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regex4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AbrirTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(regex4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regex2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regex1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regex3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AbrirTxt)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regex1)
                        .addGap(1, 1, 1)
                        .addComponent(regex2)
                        .addGap(18, 18, 18)
                        .addComponent(regex3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regex4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirTxtActionPerformed
        if (seleccionar.showDialog(null, "abrir")==JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()){
                if (archivo.getName().endsWith("txt")){
                    String documento = abrirArchivo(archivo);
                    TxtArea.setText(documento);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no compatible");
                }
            }
        }
    }//GEN-LAST:event_AbrirTxtActionPerformed

    private void regex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regex1ActionPerformed
        String texto = "";
        texto = this.TxtArea.getText();
        String resulTex = texto;
        
        
        String Concatenar = "";
        
        String [] cadenas = resulTex.split("[ ]");
     
        String array[] = new String[cadenas.length];//para almacenar las palabras extraidas del texto dinamicamente
            int contar=0;
            for(int i = 0; i<cadenas.length; i++){
                array[i]=cadenas[i];
                    contar=cadenas.length;
                
            }
      
      
            int x=0; 
            
            for (x = 0 ; x <contar; x ++){
                 
                Pattern pat = Pattern.compile("(\\bArb+[a-zA-Z]+\\b)");//Patron para encotrar las palabras
                Matcher mat = pat.matcher(array[x]);
                if (mat.matches()) {
                    //al detectar  la cadena o palabra no tiene un vocal al final ,, aumentaria ´+1
                    Concatenar += " "+array[x]; 
                } else {
                    
                }
            }
            resultado.setText(String.valueOf(Concatenar));
        
    }//GEN-LAST:event_regex1ActionPerformed

    private void regex3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regex3ActionPerformed
        String texto = "";
        texto = this.TxtArea.getText();
        String resulTex = texto;
        
        
        String Concatenar = "";
                Pattern pat = Pattern.compile("\\s?[Auto]+");//Patron para encotrar las palabras
                Matcher mat = pat.matcher(resulTex);
                
                     Concatenar = mat.replaceAll("Bicicleta");
                
            
            resultado.setText(String.valueOf(Concatenar));
        
    }//GEN-LAST:event_regex3ActionPerformed

    private void regex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regex2ActionPerformed
        String texto = "";
        texto = this.TxtArea.getText();
        String resulTex = texto;
        
        
        String Concatenar="";
        
        String [] cadenas = resulTex.split("[ ]");
     
        String array[] = new String[cadenas.length];//para almacenar las palabras extraidas del texto dinamicamente
            int contar=0;
            for(int i = 0; i<cadenas.length; i++){
                array[i]=cadenas[i];
                    contar=cadenas.length;
                
            }
      
      
            int x=0; 
      
            
            for (x = 0 ; x <contar; x ++){
                 
                Pattern pat = Pattern.compile("[A-Za-z]+");//^Mu.+
                Matcher mat = pat.matcher(array[x]);
                if (mat.matches()) {
                    //al detectar  la cadena o palabra no tiene un vocal al final ,, aumentaria ´+1
                    Concatenar += " "+array[x]; 
                } else {
                    
                } 
            }
            
            resultado.setText(String.valueOf(Concatenar));
        
    }//GEN-LAST:event_regex2ActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void regex4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regex4ActionPerformed
        String texto = "";
        texto = this.TxtArea.getText();
        String resulTex = texto;
        
        String Concatenar="";
        
        String [] cadenas = resulTex.split("[ ]");
     
        String array[] = new String[cadenas.length];//para almacenar las palabras extraidas del texto dinamicamente
            int contar=0;
            for(int i = 0; i<cadenas.length; i++){
                array[i]=cadenas[i];
                    contar=cadenas.length;
                
            }
      
      
            int x=0; 
      
            
            for (x = 0 ; x <contar; x ++){
                 
                Pattern pat = Pattern.compile("[0-9]+[+|*|/|*][0-9]+[=][0-9]+");//^Mu.+
                Matcher mat = pat.matcher(array[x]);
                if (mat.matches()) {
                    //al detectar  la cadena o palabra no tiene un vocal al final ,, aumentaria ´+1
                    Concatenar += " "+array[x]; 
                } else {
                    
                } 
            }
            resultado.setText(String.valueOf(Concatenar));
        
    }//GEN-LAST:event_regex4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirArchivoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirArchivoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirArchivoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirArchivoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirArchivoVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirTxt;
    private javax.swing.JTextArea TxtArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regex1;
    private javax.swing.JButton regex2;
    private javax.swing.JButton regex3;
    private javax.swing.JButton regex4;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
